-- Device Registration Tables
-- Supports device-dependent authentication (not phone-dependent)

-- Registration Tokens (QR Codes)
CREATE TABLE IF NOT EXISTS registration_tokens (
  token_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT,                    -- NULL for owner, set for staff
  role TEXT NOT NULL,              -- 'owner' or 'staff'
  permissions TEXT,                -- JSON array of permissions
  created_by TEXT NOT NULL,        -- Who generated this QR
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,    -- Typically 10 minutes from creation
  used_at DATETIME,                -- When the QR was scanned
  used_by_device_id TEXT,          -- Which device used this token
  is_active INTEGER DEFAULT 1,     -- Can be revoked before use
  max_uses INTEGER DEFAULT 1,      -- Usually 1, can be > 1 for staff onboarding
  use_count INTEGER DEFAULT 0,
  FOREIGN KEY (tenant_id) REFERENCES restaurant_tenants(tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_tokens_tenant ON registration_tokens(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tokens_active ON registration_tokens(is_active, expires_at);
CREATE INDEX IF NOT EXISTS idx_tokens_lookup ON registration_tokens(token_id, is_active);

-- Registered Devices
-- Each physical device must be registered individually
CREATE TABLE IF NOT EXISTS registered_devices (
  device_id TEXT PRIMARY KEY,           -- UUID generated by device
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,                -- owner_id or staff_id
  user_role TEXT NOT NULL,              -- 'owner' or 'staff'
  device_name TEXT,                     -- e.g. "Samsung Galaxy S21"
  device_model TEXT,                    -- e.g. "SM-G991B"
  device_os TEXT,                       -- e.g. "Android 13"
  device_fingerprint TEXT NOT NULL UNIQUE,  -- Hardware ID hash (unique per device)
  device_token_hash TEXT NOT NULL,      -- SHA256 hash of device token
  registered_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  registered_via TEXT DEFAULT 'qr',    -- 'qr' or 'manual'
  last_seen_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME,                  -- 90 days from registration
  is_active INTEGER DEFAULT 1,          -- Can be revoked
  revoked_at DATETIME,
  revoked_by TEXT,
  revoke_reason TEXT,
  FOREIGN KEY (tenant_id) REFERENCES restaurant_tenants(tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_devices_tenant ON registered_devices(tenant_id);
CREATE INDEX IF NOT EXISTS idx_devices_user ON registered_devices(user_id);
CREATE INDEX IF NOT EXISTS idx_devices_active ON registered_devices(is_active, expires_at);
CREATE INDEX IF NOT EXISTS idx_devices_fingerprint ON registered_devices(device_fingerprint, is_active);
CREATE INDEX IF NOT EXISTS idx_devices_lookup ON registered_devices(device_id, is_active);

-- Device Activity Log (optional, for audit trail)
CREATE TABLE IF NOT EXISTS device_activity_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  device_id TEXT NOT NULL,
  tenant_id TEXT NOT NULL,
  activity_type TEXT NOT NULL,      -- 'login', 'revoke', 'register'
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  ip_address TEXT,
  user_agent TEXT,
  metadata TEXT,                    -- JSON
  FOREIGN KEY (device_id) REFERENCES registered_devices(device_id),
  FOREIGN KEY (tenant_id) REFERENCES restaurant_tenants(tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_activity_device ON device_activity_log(device_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_activity_tenant ON device_activity_log(tenant_id, timestamp);
